//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 06:55:05 PM BST 
//


package pt.uc.dei.aor.paj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for categoriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="categoriaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="noticia" type="{}noticiaType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="tipo" type="{}categoria_tipo" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "categoriaType", propOrder = {
    "noticia"
})
public class CategoriaType {

    @XmlElement(required = true)
    protected NoticiaType noticia;
    @XmlAttribute(name = "tipo")
    protected CategoriaTipo tipo;

    /**
     * Gets the value of the noticia property.
     * 
     * @return
     *     possible object is
     *     {@link NoticiaType }
     *     
     */
    public NoticiaType getNoticia() {
        return noticia;
    }

    /**
     * Sets the value of the noticia property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticiaType }
     *     
     */
    public void setNoticia(NoticiaType value) {
        this.noticia = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriaTipo }
     *     
     */
    public CategoriaTipo getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriaTipo }
     *     
     */
    public void setTipo(CategoriaTipo value) {
        this.tipo = value;
    }

}
